version: "3.8"

services:

  # Database Postgres
  db:
    image: postgres
    #    restart: always
    container_name: postgresql_db
    volumes:
      - pgdb-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  # Django App
  web:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    container_name: portfolio_app
    image: "portfolio_app"
    restart: always
    depends_on:
      - db

volumes:
  pgdb-data:
