# Generated by Django 4.1.3 on 2022-11-18 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portfolio.apps.info.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0002_thumbnail_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.URLField(verbose_name='linkedin url')),
                ('github', models.URLField(verbose_name='github url')),
                ('stackoverflow', models.URLField(verbose_name='stackoverflow url')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='technology name')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='tech/icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('BEGNR', 'Beginner'), ('INTRM', 'Intermediate'), ('EXPRT', 'Expert')], default='INTRM', max_length=5)),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.technology')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='address')),
                ('phone_number', models.CharField(max_length=14, validators=[portfolio.apps.info.utils.phone_number_validator], verbose_name='phone number')),
                ('social', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='info.socialprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='skills',
            field=models.ManyToManyField(to='info.skill'),
        ),
    ]
