# Generated by Django 4.1.3 on 2022-11-18 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_socialprofile_technology_skill_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='info.skilltype'),
            preserve_default=False,
        ),
    ]
