# Generated by Django 4.1.3 on 2022-11-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_skilltype_skill_skill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='image_height',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='image_width',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='tech/icons/', width_field='image_width'),
        ),
    ]
