# Generated by Django 4.1.3 on 2022-11-19 11:50

from django.db import migrations, models
import portfolio.utils.image


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_remove_technology_image_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.utils.image.renamed_image_loc),
        ),
    ]
